<a href="https://colab.research.google.com/github/chaitanya6681/ACE-BOOTCAMP-JUNE26/blob/main/pandas_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
dframe=pd.read_csv('used_cars.csv')
print(dframe)

            Brand      Model  Year  Mileage_kmpl    Engine_CC  Horsepower  \
0          Toyota      Camry  2001     19.615852  1396.560379         NaN
1         Hyundai        i20  2012     19.478608  1130.771005  137.021719
2        Mahindra     Bolero  2008     17.469920  1766.466250  142.902960
3             BMW         X1  2015     21.295421          NaN   49.782079
4           Honda      Civic  2022     18.326833  1239.334935  121.505993
...           ...        ...   ...           ...          ...         ...
1004995    Nissan    Magnite  2022     12.256422  1773.657889  117.574596
1004996     Honda      Amaze  2005           NaN  1705.773023   99.643689
1004997     Skoda    Octavia  2018     21.665335  1447.159515         NaN
1004998       BMW         X3  2010     17.852635  2179.906631         NaN
1004999      Ford  Endeavour  2010     20.839002   800.000000   11.857082

        Fuel_Type Transmission Owner_Type  Color       City  Kms_Driven  \
0          Hybrid    Automatic      First   Grey    Chennai      500928
1          Petrol          NaN      First   Grey     Mumbai      211510
2             NaN    Automatic      First  Black    Kolkata      333999
3             NaN       Manual      First  White       Pune      225930
4          Diesel       Manual     Second  White    Kolkata       43404
...           ...          ...        ...    ...        ...         ...
1004995    Petrol       Manual      First  Black  Ahmedabad       68571
1004996       CNG    Automatic      First    NaN       Pune      311400
1004997    Petrol          NaN      First  Brown      Delhi       42140
1004998    Petrol       Manual      First  Brown     Mumbai      211980
1004999    Petrol       Manual      First   Blue    Kolkata      273045

         Insurance_Valid  Service_History  Accidents  Tax_Paid  \
0                      1                1          0         1
1                      0                1          0         1
2                      1                0          0         1
3                      1                1          3         1
4                      1                0          0         1
...                  ...              ...        ...       ...
1004995                1                0          0         1
1004996                1                1          0         1
1004997                0                1          0         1
1004998                0                1          0         1
1004999                1                1          0         1

         Number_of_Doors  Seats  Registration_Age         Price
0                      4      5                24  3.531896e+05
1                      4      5                13  9.596943e+05
2                      5      5                17  2.920229e+05
3                      4      5                10  2.949453e+06
4                      5      5                 3  6.365208e+05
...                  ...    ...               ...           ...
1004995                4      5                 3  1.104233e+06
1004996                4      5                20  7.122346e+05
1004997                4      4                 7  1.304198e+06
1004998                4      7                15  1.866610e+06
1004999                4      7                15  5.000000e+04

[1005000 rows x 20 columns]

In [3]:
print(dframe.head())

      Brand   Model  Year  Mileage_kmpl    Engine_CC  Horsepower Fuel_Type  \
0    Toyota   Camry  2001     19.615852  1396.560379         NaN    Hybrid
1   Hyundai     i20  2012     19.478608  1130.771005  137.021719    Petrol
2  Mahindra  Bolero  2008     17.469920  1766.466250  142.902960       NaN
3       BMW      X1  2015     21.295421          NaN   49.782079       NaN
4     Honda   Civic  2022     18.326833  1239.334935  121.505993    Diesel

  Transmission Owner_Type  Color     City  Kms_Driven  Insurance_Valid  \
0    Automatic      First   Grey  Chennai      500928                1
1          NaN      First   Grey   Mumbai      211510                0
2    Automatic      First  Black  Kolkata      333999                1
3       Manual      First  White     Pune      225930                1
4       Manual     Second  White  Kolkata       43404                1

   Service_History  Accidents  Tax_Paid  Number_of_Doors  Seats  \
0                1          0         1                4      5
1                1          0         1                4      5
2                0          0         1                5      5
3                1          3         1                4      5
4                0          0         1                5      5

   Registration_Age         Price
0                24  3.531896e+05
1                13  9.596943e+05
2                17  2.920229e+05
3                10  2.949453e+06
4                 3  6.365208e+05

In [4]:
print(dframe.head(10))

        Brand   Model  Year  Mileage_kmpl    Engine_CC  Horsepower Fuel_Type  \
0      Toyota   Camry  2001     19.615852  1396.560379         NaN    Hybrid
1     Hyundai     i20  2012     19.478608  1130.771005  137.021719    Petrol
2    Mahindra  Bolero  2008     17.469920  1766.466250  142.902960       NaN
3         BMW      X1  2015     21.295421          NaN   49.782079       NaN
4       Honda   Civic  2022     18.326833  1239.334935  121.505993    Diesel
5      Toyota   Camry  2007           NaN  1513.157430  100.927306    Petrol
6     Hyundai     i20  2014     16.328654  1398.722600  111.846497    Diesel
7     Hyundai   Creta  2001     21.895120   800.000000    0.709766    Petrol
8  Volkswagen  Taigun  2020     17.461847  1397.891768  104.095168    Diesel
9        Audi      A4  2009     12.062221  1618.723936   86.071024    Petrol

  Transmission Owner_Type  Color       City  Kms_Driven  Insurance_Valid  \
0    Automatic      First   Grey    Chennai      500928                1
1          NaN      First   Grey     Mumbai      211510                0
2    Automatic      First  Black    Kolkata      333999                1
3       Manual      First  White       Pune      225930                1
4       Manual     Second  White    Kolkata       43404                1
5    Automatic     Second    NaN        NaN      321426                0
6       Manual      First    NaN    Chennai      200343                1
7       Manual     Second  White    Kolkata      228720                1
8    Automatic    Fourth+  Black  Hyderabad      122025                1
9       Manual     Second   Blue       Pune      395200                1

   Service_History  Accidents  Tax_Paid  Number_of_Doors  Seats  \
0                1          0         1                4      5
1                1          0         1                4      5
2                0          0         1                5      5
3                1          3         1                4      5
4                0          0         1                5      5
5                0          1         1                4      2
6                0          0         1                4      4
7                0          0         1                5      5
8                1          0         1                4      5
9                1          1         1                5      7

   Registration_Age         Price
0                24  3.531896e+05
1                13  9.596943e+05
2                17  2.920229e+05
3                10  2.949453e+06
4                 3  6.365208e+05
5                18  5.195264e+05
6                11  4.953191e+05
7                24  5.000000e+04
8                 5  1.045347e+06
9                16  2.633309e+05

In [9]:
dframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005000 entries, 0 to 1004999
Data columns (total 20 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Brand             1005000 non-null  object
 1   Model             1005000 non-null  object
 2   Year              1005000 non-null  int64
 3   Mileage_kmpl      924610 non-null   float64
 4   Engine_CC         924597 non-null   float64
 5   Horsepower        924597 non-null   float64
 6   Fuel_Type         926267 non-null   object
 7   Transmission      924615 non-null   object
 8   Owner_Type        1005000 non-null  object
 9   Color             924581 non-null   object
 10  City              924570 non-null   object
 11  Kms_Driven        1005000 non-null  int64
 12  Insurance_Valid   1005000 non-null  int64
 13  Service_History   1005000 non-null  int64
 14  Accidents         1005000 non-null  int64
 15  Tax_Paid          1005000 non-null  int64
 16  Number_of_Doors   1005000 non-null  int64
 17  Seats             1005000 non-null  int64
 18  Registration_Age  1005000 non-null  int64
 19  Price             1005000 non-null  float64
dtypes: float64(4), int64(9), object(7)
memory usage: 153.4+ MB

In [18]:
dframe.iloc[1:,2]

1          2012
2          2008
3          2015
4          2022
5          2007
           ...
1004995    2022
1004996    2005
1004997    2018
1004998    2010
1004999    2010
Name: Year, Length: 1004999, dtype: int64

In [19]:
dframe.iloc[2:5,[0,9,1,2,5]]

      Brand  Color   Model  Year  Horsepower
2  Mahindra  Black  Bolero  2008  142.902960
3       BMW  White      X1  2015   49.782079
4     Honda  White   Civic  2022  121.505993

In [34]:
dframe.set_index("Model",inplace=True)

KeyError: "None of ['Model'] are in the columns"

In [4]:
dframe.loc('Model')

ValueError: No axis named Model for object type DataFrame

In [6]:
dframe

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,3.531896e+05
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,NaN,First,Grey,Mumbai,211510,0,1,0,1,4,5,13,9.596943e+05
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902960,NaN,Automatic,First,Black,Kolkata,333999,1,0,0,1,5,5,17,2.920229e+05
3,BMW,X1,2015,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,White,Kolkata,43404,1,0,0,1,5,5,3,6.365208e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004995,Nissan,Magnite,2022,12.256422,1773.657889,117.574596,Petrol,Manual,First,Black,Ahmedabad,68571,1,0,0,1,4,5,3,1.104233e+06
1004996,Honda,Amaze,2005,NaN,1705.773023,99.643689,CNG,Automatic,First,NaN,Pune,311400,1,1,0,1,4,5,20,7.122346e+05
1004997,Skoda,Octavia,2018,21.665335,1447.159515,NaN,Petrol,NaN,First,Brown,Delhi,42140,0,1,0,1,4,4,7,1.304198e+06
1004998,BMW,X3,2010,17.852635,2179.906631,NaN,Petrol,Manual,First,Brown,Mumbai,211980,0,1,0,1,4,7,15,1.866610e+06
1004999,Ford,Endeavour,2010,20.839002,800.000000,11.857082,Petrol,Manual,First,Blue,Kolkata,273045,1,1,0,1,4,7,15,5.000000e+04

In [12]:
dframe.columns

Index(['Brand', 'Model', 'Year', 'Mileage_kmpl', 'Engine_CC', 'Horsepower',
       'Fuel_Type', 'Transmission', 'Owner_Type', 'Color', 'City',
       'Kms_Driven', 'Insurance_Valid', 'Service_History', 'Accidents',
       'Tax_Paid', 'Number_of_Doors', 'Seats', 'Registration_Age', 'Price'],
      dtype='object')

In [25]:
dframe['Brand']=='BMW'

0          False
1          False
2          False
3           True
4          False
           ...
1004995    False
1004996    False
1004997    False
1004998     True
1004999    False
Name: Brand, Length: 1005000, dtype: bool

In [27]:
fi=dframe['Brand']=='BMW'
dframe.loc[fi]

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
3,BMW,X1,2008,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
20,BMW,X3,2008,19.570696,NaN,154.373826,Petrol,Automatic,Second,Red,Mumbai,328635,1,1,0,1,5,5,15,2.522184e+06
24,BMW,3 Series,2008,17.822940,1089.912293,78.973454,Petrol,Automatic,Third,NaN,Ahmedabad,121429,1,1,1,1,5,5,7,3.246262e+06
27,BMW,X3,2008,12.237087,1384.376887,80.199592,Diesel,Automatic,Third,Silver,Chennai,204708,1,1,0,1,5,7,14,1.754352e+06
48,BMW,X3,2008,22.630736,1889.931287,197.427894,CNG,Manual,Second,Silver,Delhi,104356,1,1,1,1,4,7,14,2.543034e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004928,BMW,X3,2008,21.063811,1663.687534,145.562860,CNG,Manual,First,White,Bangalore,103264,0,1,0,1,4,5,16,2.690016e+06
1004956,BMW,X1,2008,16.703533,1563.927986,103.122579,NaN,Manual,Second,NaN,Mumbai,277423,1,1,0,1,4,5,17,2.082357e+06
1004968,BMW,X3,2008,NaN,1994.409284,152.778428,Diesel,Automatic,First,Grey,Pune,43326,1,1,0,1,4,5,2,1.933235e+06
1004985,BMW,X1,2008,21.410263,1672.277752,164.591353,diesel,Manual,Second,Grey,Mumbai,82890,1,0,0,1,5,7,15,1.359402e+06
1004998,BMW,X3,2008,17.852635,2179.906631,NaN,Petrol,Manual,First,Brown,Mumbai,211980,0,1,0,1,4,7,15,1.866610e+06

In [28]:
filt=dframe['Brand']=='BMW'
dframe.loc[filt].head(10)

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
3,BMW,X1,2008,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
20,BMW,X3,2008,19.570696,NaN,154.373826,Petrol,Automatic,Second,Red,Mumbai,328635,1,1,0,1,5,5,15,2.522184e+06
24,BMW,3 Series,2008,17.822940,1089.912293,78.973454,Petrol,Automatic,Third,NaN,Ahmedabad,121429,1,1,1,1,5,5,7,3.246262e+06
27,BMW,X3,2008,12.237087,1384.376887,80.199592,Diesel,Automatic,Third,Silver,Chennai,204708,1,1,0,1,5,7,14,1.754352e+06
48,BMW,X3,2008,22.630736,1889.931287,197.427894,CNG,Manual,Second,Silver,Delhi,104356,1,1,1,1,4,7,14,2.543034e+06
83,BMW,X3,2008,18.962149,1911.992909,163.050097,Petrol,Manual,Third,Brown,Bangalore,104512,1,0,0,1,4,5,16,1.210788e+06
92,BMW,3 Series,2008,21.492230,1288.822304,116.269259,Petrol,Automatic,Second,Blue,Mumbai,159500,1,1,1,1,4,5,25,1.793533e+06
112,BMW,X3,2008,NaN,1137.820241,72.996406,Diesel,NaN,Third,Black,NaN,407631,1,1,0,1,4,5,21,2.324499e+06
124,BMW,3 Series,2008,13.527478,1545.032759,99.649106,NaN,Manual,First,Silver,Pune,20307,0,1,0,1,4,5,3,2.952209e+06
127,BMW,X1,2008,16.942514,1177.315713,96.661029,Diesel,Manual,First,Brown,Pune,535150,1,1,0,1,4,5,22,1.299008e+05

In [44]:
filt=((dframe['City']=='Hyderabad') & (dframe['Color']=='Blue') &(dframe['Brand']=='BMW'))
wdf=dframe.loc[filt].sort_index(ascending=True).head(20)
wdf.to_csv("/content/car_hyd_bmw.csv")

In [46]:
import pandas as pd
students={
    'Name':['SKC','NA','GJ','SK'],
    'Rollno':[123,124,125,126],
    'Branch':['CSM','CSE','ECE','EEE'],
    'City':['Knl','TS','EG','WRNGL']
}
print(students)
dframe=pd.DataFrame(students)
dframe
dframe.shape
dframe['Branch']
dframe.loc[0:2,['City','Branch']]

{'Name': ['SKC', 'NA', 'GJ', 'SK'], 'Rollno': [123, 124, 125, 126], 'Branch': ['CSM', 'CSE', 'ECE', 'EEE'], 'City': ['Knl', 'TS', 'EG', 'WRNGL']}

  City Branch
0  Knl    CSM
1   TS    CSE
2   EG    ECE